INSERT INTO articles (
  title,
  abstract,
  authors,
  source,
  volume,
  issue,
  category,
  tags,
  pdf_url,
  image_url,
  pdf_filename,
  cover_image_filename,
  publication_date,
  status,
  page_number,
  article_type
) VALUES (
  'IGM - Vol. 4, No. 50',
  'Ce numéro de l''Info Gazette Médicale met l''accent sur la Journée Internationale des Personnes Handicapées, avec des articles sur l''inclusion sociale en Haïti via des institutions comme L''Arche Haïti et l''Institut Montfort. Il présente des revues médicales sur l''acupuncture pour les lombalgies, la thérapie cognitivo-comportementale pour la prévention du suicide, et les liens entre vaccin zona et démence. Le numéro aborde également la communication thérapeutique en soins infirmiers, une réflexion biologique sur la mélanine, une étude de cas sur la myasthénie grave, et marque la transition de leadership au sein de la coordination du journal.',
  ARRAY['DeBar LL', 'Bryan CJ et al.', 'Polisky V et al.', 'Wong CX et al.', 'Caroline Lamothe', 'Juania Mela Mora Cuña AUGUSTE Inf. Lic', 'Phara GUERRIER Inf. Lic', 'Cassianie PIERRE Inf. Lic', 'Annaling LUCCEUS Inf. Lic', 'Moradeline ANNACIUS Inf. Lic', 'Eddy LEMAIRE', 'Louis Franck Télémaque MD'],
  'IGM',
  '4',
  '50',
  'Médecine Générale',
  ARRAY['Santé Publique', 'Handicap', 'Acupuncture', 'Suicide', 'Vaccination', 'Communication thérapeutique', 'Dermatologie', 'Myasthénie grave', 'Histoire de la médecine', 'Inclusion sociale'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/igm-pdfs/IGM_vol_04_no%2050_26_12_25.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/igm_covers/IGM_vol_04_no%2050_26_12_25.png',
  'IGM_vol_04_no 50_26_12_25.pdf',
  'IGM_vol_04_no 50_26_12_25.png',
  '2025-12-01 00:00:00+00',
  'published',
  '19',
  'IGM'
);