-- Insert missing ADC chapters into articles table
INSERT INTO public.articles (
  id,
  title,
  abstract,
  authors,
  source,
  category,
  tags,
  pdf_url,
  image_url,
  status,
  institution,
  volume,
  issue,
  page_number,
  specialty,
  article_type,
  primary_author,
  publication_date,
  views,
  citations,
  downloads,
  shares,
  cover_image_filename,
  pdf_filename,
  co_authors
) VALUES 
-- Chapter 1
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Traumatologie et Urgences',
  'Présentation des principales pathologies traumatiques rencontrées en chirurgie d''urgence, incluant les fractures, plaies et traumatismes complexes avec approches diagnostiques et thérapeutiques adaptées au contexte haïtien.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Traumatologie', 'Urgences', 'Fractures', 'Diagnostic chirurgical'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_1_maj_7_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_1_maj_7_5_24.png',
  'published',
  'Infochir',
  '',
  '01',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-07T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_1_maj_7_5_24.png',
  'ADC_ch_1_maj_7_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 2
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Abdominale',
  'Exploration des pathologies abdominales chirurgicales courantes, incluant les urgences abdominales, hernies, et affections gastro-intestinales avec techniques diagnostiques appropriées.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie abdominale', 'Urgences abdominales', 'Hernies', 'Gastro-entérologie'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_2_maj_26_6_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_2_maj_26_6_24.png',
  'published',
  'Infochir',
  '',
  '02',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-06-26T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_2_maj_26_6_24.png',
  'ADC_ch_2_maj_26_6_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 4
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Thoracique',
  'Pathologies thoraciques nécessitant une intervention chirurgicale, incluant les traumatismes thoraciques, pneumothorax, et affections pleurales avec approches diagnostiques modernes.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie thoracique', 'Pneumothorax', 'Traumatisme thoracique', 'Plèvre'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_4_maj_21_3_22.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_4_maj_21_3_22.png',
  'published',
  'Infochir',
  '',
  '04',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2022-03-21T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_4_maj_21_3_22.png',
  'ADC_ch_4_maj_21_3_22.pdf',
  ARRAY[]::text[]
),
-- Chapter 7
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Vasculaire',
  'Affections vasculaires chirurgicales incluant anévrismes, thromboses, varices et pathologies artérielles avec techniques diagnostiques vasculaires appropriées.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie vasculaire', 'Anévrismes', 'Thromboses', 'Pathologies artérielles'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_7_maj_29_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_7_maj_29_5_24.png',
  'published',
  'Infochir',
  '',
  '07',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-29T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_7_maj_29_5_24.png',
  'ADC_ch_7_maj_29_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 8
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Orthopédique',
  'Pathologies orthopédiques et traumatologiques incluant fractures complexes, luxations, et affections ostéo-articulaires avec approches chirurgicales modernes.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Orthopédie', 'Traumatologie', 'Fractures', 'Luxations', 'Ostéo-articulaire'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_8_maj_16_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_8_maj_16_5_24.png',
  'published',
  'Infochir',
  '',
  '08',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-16T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_8_maj_16_5_24.png',
  'ADC_ch_8_maj_16_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 9
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Urologique',
  'Pathologies urologiques chirurgicales incluant lithiases, tumeurs urogénitales, et malformations avec techniques diagnostiques urologiques spécialisées.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Urologie', 'Lithiases', 'Tumeurs urogénitales', 'Malformations'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_9_maj_29_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_9_maj_29_5_24.png',
  'published',
  'Infochir',
  '',
  '09',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-29T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_9_maj_29_5_24.png',
  'ADC_ch_9_maj_29_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 10
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Pédiatrique',
  'Pathologies chirurgicales pédiatriques spécialisées incluant malformations congénitales, urgences pédiatriques, et techniques adaptées à l''enfant.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie pédiatrique', 'Malformations congénitales', 'Urgences pédiatriques'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_10_maj_16_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_10_maj_16_5_24.png',
  'published',
  'Infochir',
  '',
  '10',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-16T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_10_maj_16_5_24.png',
  'ADC_ch_10_maj_16_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 11
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Plastique et Reconstructrice',
  'Techniques de chirurgie plastique et reconstructrice incluant greffes, lambeaux, et reconstruction post-traumatique avec approches esthétiques et fonctionnelles.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie plastique', 'Reconstruction', 'Greffes', 'Lambeaux'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_11_maj_29_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_11_maj_29_5_24.png',
  'published',
  'Infochir',
  '',
  '11',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-29T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_11_maj_29_5_24.png',
  'ADC_ch_11_maj_29_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 12
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Digestive',
  'Pathologies digestives chirurgicales incluant cancers digestifs, occlusions, et chirurgie hépatobiliaire avec techniques diagnostiques spécialisées.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie digestive', 'Cancers digestifs', 'Occlusions', 'Hépatobiliaire'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_12_maj_29_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_12_maj_29_5_24.png',
  'published',
  'Infochir',
  '',
  '12',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-29T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_12_maj_29_5_24.png',
  'ADC_ch_12_maj_29_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 13
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Neurochirurgie',
  'Pathologies neurochirurgicales incluant traumatismes crâniens, tumeurs cérébrales, et affections rachidiennes avec techniques diagnostiques neurochirurgicales.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Neurochirurgie', 'Traumatismes crâniens', 'Tumeurs cérébrales', 'Rachis'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_13_maj_29_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_13_maj_29_5_24.png',
  'published',
  'Infochir',
  '',
  '13',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-29T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_13_maj_29_5_24.png',
  'ADC_ch_13_maj_29_5_24.pdf',
  ARRAY[]::text[]
),
-- Chapter 15
(
  gen_random_uuid(),
  'Atlas De Diagnostic Chirurgicale (ADC) - Chirurgie Gynécologique',
  'Pathologies gynécologiques chirurgicales incluant tumeurs ovariennes, fibromes utérins, et chirurgie pelvienne avec approches diagnostiques spécialisées.',
  ARRAY['Dr. Louis-Franck TÉLÉMAQUE'],
  'ADC',
  'Chirurgie',
  ARRAY['Chirurgie gynécologique', 'Tumeurs ovariennes', 'Fibromes', 'Chirurgie pelvienne'],
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas-pdfs/ADC_ch_15_maj_29_5_24.pdf',
  'https://llxzstqejdrplmxdjxlu.supabase.co/storage/v1/object/public/atlas_covers/ADC_ch_15_maj_29_5_24.png',
  'published',
  'Infochir',
  '',
  '15',
  '',
  'Chirurgie',
  'INDEX',
  'Dr. Louis-Franck TÉLÉMAQUE',
  '2024-05-29T00:00:00+00:00',
  0,
  0,
  0,
  0,
  'ADC_ch_15_maj_29_5_24.png',
  'ADC_ch_15_maj_29_5_24.pdf',
  ARRAY[]::text[]
);