// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llxzstqejdrplmxdjxlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxseHpzdHFlamRycGxteGRqeGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNzM3NDgsImV4cCI6MjA1MDY0OTc0OH0.dza-_2f6kCnY11CmnyHRf3kE-JxQTTnZm20GaZwiA9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Gets a public URL for a file in a Supabase storage bucket
 */
export const getStorageUrl = (bucketName: string, fileName: string): string => {
  if (!fileName) return '';
  if (fileName.startsWith('http')) return fileName;
  
  const { data } = supabase.storage
    .from(bucketName)
    .getPublicUrl(fileName);
  
  return data.publicUrl;
};

/**
 * Gets a public URL for an ADC cover image
 */
export const getADCCoverUrl = (fileName: string): string => {
  return getStorageUrl('atlas_covers', fileName);
};

/**
 * Gets a public URL for a founder avatar
 */
export const getFounderAvatarUrl = (fileName: string): string => {
  return getStorageUrl('founder_avatars', fileName);
};